site_title = "Security RSS Dashboard"

cache_max_days = 7
cache_url = "https://mikaelkall.github.io/security-rss/cache.json"
minify = true

sources = [
"https://cvedaily.com/feed.xml",
"https://cvedaily.com/feed-critical.xml",
"https://www.exploit-db.com/rss.xml",
"https://packetstormsecurity.com/files/feed/"
]